plugins {
    id 'java'
    id 'jacoco'
}

group = 'org.CustomTrie'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

sourceSets {
    jmh {
        java.srcDirs = ['src/jmh/java']
        resources.srcDirs = ['src/jmh/resources']
        compileClasspath += sourceSets.main.output + sourceSets.main.compileClasspath
        runtimeClasspath += sourceSets.main.output + sourceSets.main.runtimeClasspath
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    jmhImplementation 'org.openjdk.jmh:jmh-core:1.37'
    jmhAnnotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess:1.37'
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

task jmh(type: JavaExec, dependsOn: 'jmhClasses') {
    mainClass = 'org.openjdk.jmh.Main'
    classpath = sourceSets.jmh.runtimeClasspath
    args 'CustomTrie.CustomTriePerformanceTest'
}

jacocoTestReport {
    dependsOn test

    reports {
        xml.required = true
        html.required = true
    }

    afterEvaluate {
        classDirectories.setFrom(
                files(classDirectories.files.collect {
                    fileTree(dir: it, exclude: ['**/*Test.class', '**/*IT.class', '**/*PerformanceTest.class', '**/*PerformanceBenchmark.class'])
                })
        )
    }
}